### ISSUE TITLE
Show repositories link in generated file no longer works

### ISSUE THREAD

**Issue by goneall** [lfscanning/scaffold#67]
The HTML reports at the top have a link that toggles to show/hide the repos that were scanned for the project.  The link is not working and nothing is being shown.
 
Here is an example:
https://lfscanning.org/reports/omp/cobol-programming-course-2023-10-11-f88d8479-f2b8-4c50-b11e-ee0373123c04.html
 
Snapshot on: 2023-10-11 (show repos)
 
 
Click on the (show repos) text and nothing is shown, but the text does toggle.  It should be showing the list of repos.  I’ve tried this on multiple reports, all for the same OMP project.

**Comment by goneall** [comment]
It looks like this was introduced with PR #64 

The drop down is populated from the `sp._code_repos` property which appears to no longer be populated.

**Comment by jeffcshapiro** [comment]
FYI - reports generated where the repos are hosted on Gerrit & not GitHub do not seem to have this issue and are showing the repos as expected at the top of the report when toggled.

**Comment by jeffcshapiro** [comment]
this is not urgent but would be nice to fix in the next several weeks, say in January

**Comment by goneall** [comment]
@jeffcshapiro - I'll take a look at this tomorrow and see if we can get this into the same update as the fix for #68
