### ISSUE TITLE
How many months back will scaffold search for reuser?

### ISSUE THREAD

**Issue by jeffcshapiro** [lfscanning/scaffold#68]
Do we know how many months back for previous scans for a project that scaffold will search for doing the reuser for an incremental scan?

I think it might be the previous 12 months, but can't confirm easily without doing a scan, and might need this extended to a longer time frame, perhaps 24 months.

**Comment by jeffcshapiro** [comment]
I have confirmed it's only going back 12 months:
`cncf/grpc: no prior upload found in preceding 12 months, skipping reuser
`
We should make this 24 months if it's not too much work.

**Comment by jeffcshapiro** [comment]
if this is a quick fix can we get this in the next week?

**Comment by goneall** [comment]
> if this is a quick fix can we get this in the next week?

I'll start working on it on Wednesday - have a talk in San Diego on Tuesday.

**Comment by jeffcshapiro** [comment]
Sounds good, please coordinate with me before pushing any new code to production so we can be sure that Scaffold is not running.
